#!/bin/bash

# Create bundles of the list of directories and move them to ~/backup directory.
~/bin/process_dir_list ~/bin/backup/commit_and_bundle ~/bin/backup/dir_list

# Copy the bundles to external drive.
cp ~/backup/* '/run/media/busycaesar/DEV SHAH/MachineBackup/'
