#!/bin/bash

# Check if directory path is passed as argument
if [ -z "$1" ]; then
  echo "Usage: $0 <directory>"
  exit 1
fi

SCRIPT_DIR=$(dirname "$(realpath "$0")")
CONFIG_FILE_LOCATION="$SCRIPT_DIR/.env.config"

# Check if the configuration file exists
if [ -f "$CONFIG_FILE_LOCATION" ]; then
  source "$CONFIG_FILE_LOCATION"
else
  echo "config not found! Please create a config file in the current directory. For more details, visit: https://github.com/busycaesar/Linux_Bin_Scripts/blob/Master/backup/config"
  exit 1
fi

PROJECT_DIR="$1"

# Check if the provided project directory exists
if [ ! -d "$PROJECT_DIR" ]; then
  echo "Directory $PROJECT_DIR does not exist!"
  exit 1
fi

# Create output directory if it doesn't exist
mkdir -p "$DEFAULT_OUTPUT"

# Navigate to the project directory
cd "$PROJECT_DIR" || exit

# Check if the directory is a git repository
if [ ! -d ".git" ]; then
  echo "This is not a Git repository: $PROJECT_DIR"
  exit 1
fi

# Commit all changes
git add -A

if git diff --cached --quiet; then
  echo "No changes to commit"
else
  COMMIT_MESSAGE="Automated commit on $(date)"
  git commit -m "$COMMIT_MESSAGE"
fi

# Create a bundle of the repository
BUNDLE_NAME="$(basename "$PROJECT_DIR").bundle"
git bundle create "$BUNDLE_NAME" --all

# Move the bundle to the output directory
mv -f "$BUNDLE_NAME" "$DEFAULT_OUTPUT/"

# Print success message
echo "Commit made and bundle created at: $DEFAULT_OUTPUT/$BUNDLE_NAME"
